stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  image: node:20
  script:
    - npm ci
  only:
    - merge_requests
    - pushes

test:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm run test:coverage
  only:
    - merge_requests
    - pushes