
FROM node:20-alpine

WORKDIR ../app

COPY package.json .

ARG UID=1000
ARG GID=1000

RUN addgroup -gid ${GID}
RUN adduser --uid ${UID} --gid ${GID}

COPY --chown=appuser:appgroup . .

HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD curl -f http://localhost:5000/health || exit 1

RUN npm install

COPY server.js .

ENV PORT=5000

EXPOSE 5000

CMD ["node", "server.js"]
